### ISSUE TITLE
Unable to install OpenSlide without sudo

### ISSUE THREAD

**Issue by Hryniewska** [openslide/openslide-python#131]
## Context

**Operating system**: Ubuntu server 

## Details

It is almost impossible to build Openslide from a source code on a server (without sudo). There are so many dependencies that after installing one missing dependency, the other appears. Please provide access to your library only by installing it by pip, and not by installing `sudo apt-get install python3-openslide` and then `pip install openslide-python`.

It is not only my problem, [please see here](https://stackoverflow.com/questions/54857241/install-openslide-and-its-dependency-openjpeg-on-ubuntu-without-root-privileges). Unfortunately, the answer to the question on Stack Overflow is still not enough to install OpenSlide. You have to build and install many other missing dependencies.

**Comment by bgilbert** [comment]
OpenSlide does have a moderately large number of dependencies.  None of them are trivial, though: we're careful to only add a dependency if it's important for OpenSlide's functionality.

It's unfortunate that many Linux package managers require installing packages as root.  However, working around that requirement is not in scope for the OpenSlide project.  On Windows, where we didn't really have an alternative, we implemented our own [build system](https://github.com/openslide/openslide-winbuild/) for OpenSlide and all of its dependencies.  That system has been a significant maintenance burden, since it requires us to be responsible for updating all of the dependencies for bugfixes and security fixes.  On Linux, where package managers already exist, the OpenSlide project shouldn't take on this additional work.

It's possible to build and install OpenSlide Python, OpenSlide, and all of its dependencies from source without root access.  That might be a suitable workaround for a motivated user.  You might also consider alternative approaches, such as running your software in a container or a VM.
