### ISSUE TITLE
About a reverse of `_get_tile_info` (DeepZoomGenerator)

### ISSUE THREAD

**Issue by alamie** [openslide/openslide-python#154]
## Context

The [`_get_tile_info`](https://github.com/openslide/openslide-python/blob/fc14e86577a6f1be3d6b1118d839f1e2d70a0197/openslide/deepzoom.py#L185) method of the `DeepZoomGenerator` class takes as input the level and address of a tile and returns the parameters for [`read_region`](https://github.com/openslide/openslide-python/blob/fc14e86577a6f1be3d6b1118d839f1e2d70a0197/openslide/__init__.py#L347): level 0 tile address, slide level and level 0 tile size. What would be the reverse mapping of `_get_tile_info`? Unless I am mistaken, the openslide-python library does not have a function which would convert a region from a given level to another level (e.g. convert region coordinates and size from level 0 to level 1). What would it look like? Is there such a function somewhere?

**Operating system** : Mac OS 12.3.1
**OpenSlide Python version** : 1.1.2

**Comment by bgilbert** [comment]
As I understand it, you're asking about converting coordinates between levels in the OpenSlide object?  That isn't exactly the reverse mapping of `_get_tile_info`, since the latter converts from Deep Zoom coordinates to OpenSlide coordinates.

When converting between OpenSlide levels, the offsets stay the same, and the sizes should be scaled by the ratio of the level downsamples.  (Level 0 always has a downsample of 1.)
