### ISSUE TITLE
Deprecate python-3.6 support

### ISSUE THREAD

**Issue by jaharkes** [openslide/openslide-python#161]
## Details

Python-3.6 has been EOL since December 23, 2021 and various Python packages are starting to drop support for it.

Pillow-8.4.0 is the last version with 3.6 support, they are at version 9.1.1 by now.
Our 'development dependencies' (pre-commit and pytest?) have also dropped support in recent versions.

**Comment by bgilbert** [comment]
The default Python 3 in RHEL 8 is 3.6, but newer versions are available in AppStreams.  Debian stable has 3.9 and Ubuntu 20.04 LTS has 3.8.  Ubuntu 18.04 LTS has 3.6, but there's been a newer LTS version for over a year, so I don't think this matters.

I think it's reasonable to drop 3.6 support, especially since we're dropping other Python versions in this release.
