### ISSUE TITLE
OpenSlideError: Huffman table 0x00 was not defined

### ISSUE THREAD

**Issue by martvanrijthoven** [openslide/openslide-python#166]
## Context

**Issue type**: bug report / question
**Operating system**: CentOS Linux release 7.9.2009
**Platform**: 64-bit x86
**OpenSlide Python version**: 1.1.2 
**OpenSlide version**: 3.4.1 
**Slide format**: tiff

## Details

When trying to read a thumbnail/region on CentOS Linux release 7.9.2009 I get the following error:

---------------------------------------------------------------------------
OpenSlideError                            Traceback (most recent call last)
Input In [9], in <cell line: 1>()
----> 1 image.get_thumbnail((512,512))

File /usr/local/lib/python3.8/site-packages/openslide/__init__.py:134, in AbstractSlide.get_thumbnail(self, size)
    131 downsample = max(*[dim / thumb for dim, thumb in
    132         zip(self.dimensions, size)])
    133 level = self.get_best_level_for_downsample(downsample)
--> 134 tile = self.read_region((0, 0), level, self.level_dimensions[level])
    135 # Apply on solid background
    136 bg_color = '#' + self.properties.get(PROPERTY_NAME_BACKGROUND_COLOR,
    137         'ffffff')

File /usr/local/lib/python3.8/site-packages/openslide/__init__.py:228, in OpenSlide.read_region(self, location, level, size)
    218 def read_region(self, location, level, size):
    219     """Return a PIL.Image containing the contents of the region.
    220 
    221     location: (x, y) tuple giving the top left pixel in the level 0
   (...)
    226     Unlike in the C interface, the image data returned by this
    227     function is not premultiplied."""
--> 228     return lowlevel.read_region(self._osr, location[0], location[1],
    229             level, size[0], size[1])

File /usr/local/lib/python3.8/site-packages/openslide/lowlevel.py:214, in read_region(slide, x, y, level, w, h)
    212     return PIL.Image.new('RGBA', (w, h))
    213 buf = (w * h * c_uint32)()
--> 214 _read_region(slide, buf, x, y, level, w, h)
    215 return _load_image(buf, (w, h))

File /usr/local/lib/python3.8/site-packages/openslide/lowlevel.py:151, in _check_error(result, func, args)
    149 err = get_error(args[0])
    150 if err is not None:
--> 151     raise OpenSlideError(err)
    152 return _check_string(result, func, args)

OpenSlideError: Huffman table 0x00 was not defined

----

I don't get this error on e.g., Ubuntu20.04 with the same image. Could you please let me know what this error means?

Best wishes,
Mart

**Comment by bgilbert** [comment]
It appears your slide file is encoded in a way that can't be read by older versions of libjpeg-turbo.  libjpeg-turbo 1.3.90 added a fallback to the default Huffman tables when a JPEG header does not include them (see item 3 of [this changelog section](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/ChangeLog.md#1390-14-beta1)), but CentOS 7.9 ships libjpeg-turbo 1.2.90.

If possible, upgrade to a newer OS.  Alternatively, you may be able to work around this issue by building a newer version of libjpeg-turbo from source.  However, overriding core system libraries can be tricky, so use caution.  At a minimum, install into a separate installation directory rather than overwriting the system copy of the library.

**Comment by martvanrijthoven** [comment]
Dear Benjamin Gilbert,

Thank you for your message, clear explanation, and suggestions. Very much appreciated!

Best wishes,
Mart
