### ISSUE TITLE
Integer division bug

### ISSUE THREAD

**Issue by andrewmfiorillo** [openslide/openslide-python#19]
Hello,

This snippet on line 85 of openslide.deepzoom.py
`            z_size = tuple(max(1, int(math.ceil(z / 2))) for z in z_size)`

should almost definitely read
`            z_size = tuple(max(1, int(math.ceil(z / 2.0))) for z in z_size)`

In the case of images where either dimension is not a power of 2 the first line causes rounding errors which result in the incorrect number of blocks.

**Comment by bgilbert** [comment]
Hi @andrewmfiorillo!  Those two lines are equivalent.  In `openslide.deepzoom`, the `/` operator performs floating-point division: on Python 2 because of the `from __future__ import division` directive, and on Python 3 because `/` is always floating-point.

> In the case of images where either dimension is not a power of 2 the first line causes rounding errors which result in the incorrect number of blocks.

Are you seeing this effect with an actual image file?  If so, what are the DeepZoomGenerator's `tile_size`, `overlap`, `level_tiles`, and `level_dimensions`?

**Comment by andrewmfiorillo** [comment]
Hi @bgilbert!

I was seeing this issue on a skinned down Deepzoom generator heavily based on deepzoom.py, but apparently missing the `from __future__ import division` directive. In my version, switching to the second line corrected the issue so I would expect being unable to reproduce it using an exact clone.

Sorry for the false alarm!
