### ISSUE TITLE
No Windows binary wheels for Python 3.13

### ISSUE THREAD

**Issue by Liebenfiels** [openslide/openslide-python#282]
### Operating system

Windows 11

### Platform

64-bit

### OpenSlide Python version

1.3.1

### OpenSlide version

1.3.1

### Slide format

svs (pip install problem)

### Issue details

I have been using the version 3.12.4 with no problem with 
**pip install openslide-python**
Now in Python version 3.13 I tried but it does not work

Multiple errors there with some wheel build error too
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (openslide-python)
Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

This Microsoft Visual I installed and makes no difference and I dont even use it.

From simply library install task it become difficult now use it in Python 3.13 (could be their fault as works in 3.12.4). 
Can you make it work please as before out of box or **provide please simple instruction step by step** how to make it work in 3.13
I am re-verting to 3.12.4 as have no time to play with it for now.
I logged error on Python GitHub but they relayed me here, not sure could be on their Python fault
Thank you
Michal

**Comment by bgilbert** [comment]
Yes, we haven't uploaded OpenSlide Python binaries for Python 3.13 yet.  There will be a new OpenSlide Python release in the next week or two that uses the Python [Stable ABI](https://docs.python.org/3/c-api/stable.html#stable-abi), so we won't have to keep doing this for every Python release.

**Comment by Liebenfiels** [comment]
Thank you- your library generally is excellent product and allows me to open slides from histology scanner like .svs .ndpi.  
I am learning Python and made program that utilises your library and feel your pain. 
They do upgrade after upgrade and need to catch up myself to ensure the changes will not derail the code like python 2 to 3 migration as I read there was a lot of havoc even with basic arithmetic.
I guess that will apply to lots of libraries that may need to adapt.

**Comment by bgilbert** [comment]
Thank you!  I'm glad OpenSlide Python has been useful for you.

Most Python packages should handle the 3.13 upgrade with no issues.  OpenSlide Python is slightly unusual because it has a C extension module, and those usually have to be recompiled (with no source code changes needed) for every Python release.

**Comment by bgilbert** [comment]
OpenSlide Python 1.4.0 has been released and should be installable into a 64-bit installation of Python 3.13 on Windows.

**Comment by bgilbert** [comment]
Yes, you can either `pip install openslide-bin` or download OpenSlide binaries as you did before.  On Windows, both are essentially the same.  (On Linux and macOS, there can be good reasons to install OpenSlide from the system's package manager instead of `pip`, but Windows users don't have that option.)
