### ISSUE TITLE
ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?

### ISSUE THREAD

**Issue by clementgr** [openslide/openslide-python#57]
## Context

**Issue type** : bug report
**Operating system** : Mac OS 10.14.5
**Platform** : 
**OpenSlide Python version** : openslide-python 1.1.1
**Slide format** : any

## Details

hi, I am trying to install openslide-python 1.1.1 on Mac OS 10.14.5 (in a virtualenv environment) with the command :

`
pip install openslide-python
`

I am facing this error when typing `import openslide` in a python shell :

```
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/openslide/lowlevel.py", line 44, in <module>
    _lib = cdll.LoadLibrary('libopenslide.0.dylib')
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/anaconda3/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libopenslide.0.dylib, 6): image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../lib/python3.6/site-packages/openslide/__init__.py", line 29, in <module>
    from openslide import lowlevel
  File ".../lib/python3.6/site-packages/openslide/lowlevel.py", line 55, in <module>
    "Is OpenSlide installed?")
ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?

```
Please advise.

Thanks

**Comment by clementgr** [comment]
@Cao Minh Vu (on stackoverflow) worked this out for me  :

to use `openslide-python` on a Mac, you need to install the `openslide` package first.

to do so, type `brew install openslide` in a command shell (if you don't have homebrew installed, install it, it is quick and easy).

once `openslide` is installed, you can type `pip install openslide-python` in a command shell.

eventually, `import openslide` will work!!

**Comment by bgilbert** [comment]
Glad you got it working.  Closing.

**Comment by DRSEI** [comment]
Hi, I'm still experiencing the same issue even though I followed your suggestion. I received a message saying "openslide 3.4.1_7 is already installed and up-to-date" and tried to reinstall it with "brew reinstall openslide", but the problem persists. I also tried to install "openslide-python" with "pip install openslide-python", but it seems that the package is already installed. Despite these attempts, I am still getting the same error. Do you have any ideas on how to fix this issue?`Error: dlopen(libopenslide.0.dylib, 0x0006): tried: 'libopenslide.0.dylib' (no such file), '[/System/Volumes/Preboot/Cryptexes/OSlibopenslide.0.dylib](https://file+.vscode-resource.vscode-cdn.net/System/Volumes/Preboot/Cryptexes/OSlibopenslide.0.dylib)' (no such file), '[/opt/anaconda3/envs/pathml/lib/python3.8/lib-dynload/../../libopenslide.0.dylib](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/pathml/lib/libopenslide.0.dylib)' (no such file), '[/opt/anaconda3/envs/pathml/bin/../lib/libopenslide.0.dylib](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/pathml/lib/libopenslide.0.dylib)' (no such file), '[/usr/lib/libopenslide.0.dylib](https://file+.vscode-resource.vscode-cdn.net/usr/lib/libopenslide.0.dylib)' (no such file, not in dyld cache), 'libopenslide.0.dylib' (no such file), '[/usr/local/lib/libopenslide.0.dylib](https://file+.vscode-resource.vscode-cdn.net/usr/local/lib/libopenslide.0.dylib)' (no such file), '[/usr/lib/libopenslide.0.dylib](https://file+.vscode-resource.vscode-cdn.net/usr/lib/libopenslide.0.dylib)' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:
...
     57                     "Is OpenSlide installed?")
     58         _lib = cdll.LoadLibrary(_lib)
     59 else:

ImportError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed?`

**Comment by ntempier** [comment]
Hello,
i am experiencing a similar issue, the difference is that I am trying to import openslide from a specific python eg 3D slicer python console 

when i do import openslide from terminal - python it works because i installed openslide and openslide-python but 
fro the python console of the software i use i get the error : 
`Traceback (most recent call last):
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/openslide/lowlevel.py", line 69, in <module>
    _lib = cdll.LoadLibrary('libopenslide.0.dylib')
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libopenslide.0.dylib, 0x0006): tried: 'libopenslide.0.dylib' (relative path not allowed in hardened program), '/System/Volumes/Preboot/Cryptexes/OSlibopenslide.0.dylib' (no such file), '/Applications/Slicer.app/Contents/MacOS/../libopenslide.0.dylib' (no such file), '/Volumes/D/S/S-0-build/CTK-build/CMakeExternals/Install/lib/libopenslide.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Volumes/D/S/S-0-build/CTK-build/CMakeExternals/Install/lib/libopenslide.0.dylib' (no such file), '/Volumes/D/S/S-0-build/teem-build/bin/libopenslide.0.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Volumes/D/S/S-0-build/teem-build/bin/libopenslide.0.dylib' (no such file), '/usr/lib/libopenslide.0.dylib' (no such file, not in dyld cache), 'libopenslide.0.dylib' (relative path not allowed in hardened program), '/usr/lib/libopenslide.0.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/openslide/__init__.py", line 30, in <module>
    from openslide import lowlevel
  File "/Applications/Slicer.app/Contents/lib/Python/lib/python3.9/site-packages/openslide/lowlevel.py", line 78, in <module>
    raise ModuleNotFoundError(
ModuleNotFoundError: Couldn't locate OpenSlide dylib.  Is OpenSlide installed correctly?  https://openslide.org/api/python/#installing`

is there a way to link the installer openslide or to copy files so they get detected in the python console ? 

i made it work in another  computer but cannot make it work in my new one ..

Thanks in advance for the help,

Nicolas

**Comment by antonythasan20-05-00** [comment]
@gsharpminor I have the same problem. Did you solve the problem, and if so, how?

Thank you in advance. :)

**Comment by gsharpminor** [comment]
Antony--Yes and no. I've been able to get openslide installed & running by using conda package manager in a conda environment.But outside that environment, the package installed with pip still fails to import, even though it claims to have installed the latest version. So conda is a viable workaround, but still havent figured out the original issue. On Sep 4, 2023, at 05:49, antonythasan20-05-00 ***@***.***> wrote:﻿
@gsharpminor I have the same problem. Did you solve the problem, and if so, how?
Thank you in advance. :)

**Comment by yuxiaokang-source** [comment]
I use `conda install openslide-python` instead of `pip install openslide-python`, the issue was solved

**Comment by bgilbert** [comment]
On Apple silicon, Homebrew no longer installs libraries into the system's search path; see discussion in https://github.com/Homebrew/brew/issues/13481.  If you use Homebrew's version of Python, OpenSlide Python should still correctly find OpenSlide.  If you use the system Python, you'll need to do something like:

```python
import os
path = os.environ.get('DYLD_FALLBACK_LIBRARY_PATH', '')
path += (':' if path else '') + '/opt/homebrew/lib'
os.environ['DYLD_FALLBACK_LIBRARY_PATH'] = path
import openslide
```

Note that the `DYLD_FALLBACK_LIBRARY_PATH` environment variable can't be set from the shell in the usual way, because macOS won't pass it through to the system Python.
