### ISSUE TITLE
Failed to install openslide on linux server

### ISSUE THREAD

**Issue by yelaboratory** [openslide/openslide-python#72]
## Context

**Issue type** (bug report or feature request): 

Installation issue on server. 

Openslide has been installed in our supercomputer center server. So, I used following steps to add openslide python to my account environment:

module load openslide/3.4.1
pip install openslide-python

When I import openslide using jupyter notebook, it seems that OpenSlide Python still can't find the OpenSlide library.  What should I do? 

OSError: libopenslide.so.0: cannot open shared object file: No such file or directory

**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10):  Linux

**OpenSlide Python version** (`openslide.__version__`):  latest version

**OpenSlide version** (`openslide.__library_version__`): 3.4.1

**Comment by Aakanksha-Rana** [comment]
just install it as: sudo apt-get install python-openslide.

**Comment by pranathichunduru** [comment]
Hi I am facing a similar issue. However I cannot do `sudo apt-get install python-openslide` or `yum install openslide` since I am not the root user. Here is the link to my github issue. 
[https://github.com/openslide/openslide/issues/288]
If anyone had encountered a similar issue please post your working solution.
 Thanks !

**Comment by bgilbert** [comment]
@yelaboratory It sounds as though your system has been misconfigured.  If `libopenslide.so.0` is installed in a non-standard library path, its containing directory should be added to `/etc/ld.so.conf`.  If you don't have access to do that, you can add that directory to the `LD_LIBRARY_PATH` environment variable.

**Comment by JunMa11** [comment]
> Hi I am facing a similar issue. However I cannot do `sudo apt-get install python-openslide` or `yum install openslide` since I am not the root user. Here is the link to my github issue. [https://github.com/[openslide/openslide/issues/288](https://github.com/openslide/openslide/issues/288)] If anyone had encountered a similar issue please post your working solution. Thanks !

Hi @pranathichunduru ,  have you solved this problem? I have a similar one.

**Comment by amirakbarnejad** [comment]
Hi, 
After cloning the open-slide repository, I did the following:
./configure --prefix=$HOME/mylibfiles/ --no-create  && make && make install
pip download --no-deps openslide-python 
pip install openslide-python-1.1.2.tar.gz //or any other file which is downloaded by pip download

Afterwards I was getting the following error:  "OSError: libopenslide.so.0: cannot open shared object file: No such file or directory"
To solve the above error, one can do:
export LD_LIBRARY_PATH=$HOME/mylibfiles/
so that os can find the library file.
I hope it helps.
