### ISSUE TITLE
CPU multi-threading throttling issue

### ISSUE THREAD

**Issue by kleingeo** [openslide/openslide-python#75]
I have recently noticed some functions used in openslide, specifically color shifting ones (like rgb to hsv) are multi-threaded by nature without any number of thread options within the module itself.

**Comment by bgilbert** [comment]
OpenSlide and OpenSlide Python are thread-safe but generally don't start their own threads.

The `hamamatsu` format driver is an exception; it starts a short-lived background thread on `openslide_open()` to scan the slide file for restart markers.  This thread cannot be disabled, but I wouldn't expect it to affect steady-state performance that much.  (It's I/O-bound rather than CPU-bound.)
