### ISSUE TITLE
open slide and multiprocessing

### ISSUE THREAD

**Issue by pozinNicolas** [openslide/openslide-python#84]
Hi,
I am using openslide, it seems the code runs in parallel.
Is there a way to impose openslide operations to run on a single proc?

Thanks in advance
Nicolas

**Comment by bgilbert** [comment]
OpenSlide and OpenSlide Python are thread-safe but generally don't start their own threads.

The `hamamatsu` format driver is an exception; it starts a short-lived background thread on `openslide_open()` to scan the slide file for restart markers.  This thread cannot be disabled, but I wouldn't expect it to affect steady-state performance that much.  (It's I/O-bound rather than CPU-bound.)
